### ISSUE TITLE
Question: How to get html element specific api's ?

### ISSUE THREAD

**Issue by gingters** [IEvangelist/blazorators#33] opened 2022-04-22 08:17 UTC
Hi,

I'd like to use Blazorators with the Canvas API.

But what do I need to put in the implementation property of the attribute to generate the API's? In JS, you'd need to get hold of the html element's reference and then call getContext on it to get the canvas reference, for example: `document.getElementById('id').getContext();`.
How would I define this in the attribute?

**Comment by IEvangelist** [comment] 2022-04-22 13:41
Hi @gingters - I have not yet explored building out a source generator for the canvas APIs, or really any of the DOM-specific APIs. This is rather intentional. Blazor itself is preferred for DOM interactions, and for the canvas APIs, I believe there are already several really good libraries.

I do not believe that this is something that would be supported immediately. As of right now, my focus is to build out a separate library from this one that will serve as a more generic TypeScript parser. Then I'd come back here and upgrade this to rely on that library.

**Comment by IEvangelist** [comment] 2022-06-06 23:09
I'm going to close this as it is by design

**Closed by IEvangelist** 2022-06-06 23:09 UTC
